import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { GateDefinition } from "./types.js";

/**
 * Gate templates by language (G27): the verification ladder a project gets
 * when it ships no `gates.toml`, detected from its manifests. `sekhemet
 * gates init` writes the detected template out so the project can pin and
 * edit it.
 */
export type GateTemplateId = "pnpm" | "npm" | "yarn" | "python" | "rust" | "go";

function gate(
  id: string,
  rung: GateDefinition["rung"],
  layer: GateDefinition["layer"],
  command: string,
  args: string[],
  parser: string,
  timeoutMs = 300_000,
): GateDefinition {
  return { id, rung, layer, command, args, timeoutMs, parser, blocking: true };
}

function scripts(root: string): Record<string, string> {
  try {
    return (
      (
        JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
          scripts?: Record<string, string>;
        }
      ).scripts ?? {}
    );
  } catch {
    return {};
  }
}

function jsTemplate(pm: "pnpm" | "npm" | "yarn", root: string): GateDefinition[] {
  const s = scripts(root);
  const run = (script: string) => (pm === "npm" ? ["run", script] : [script]);
  const out: GateDefinition[] = [];
  const typecheck = s.typecheck ? "typecheck" : s.build ? "build" : undefined;
  if (typecheck)
    out.push(gate("typecheck", "typecheck", "static", pm, run(typecheck), "tsc", 180_000));
  else if (existsSync(join(root, "tsconfig.json"))) {
    out.push(
      gate(
        "typecheck",
        "typecheck",
        "static",
        pm === "npm" ? "npx" : pm,
        pm === "npm" ? ["tsc", "--noEmit"] : ["exec", "tsc", "--noEmit"],
        "tsc",
        180_000,
      ),
    );
  }
  if (s.lint)
    out.push(
      gate(
        "lint",
        "lint",
        "static",
        pm,
        run("lint"),
        s.lint.includes("biome") ? "biome" : "eslint",
        120_000,
      ),
    );
  if (s.test) {
    const parser = /vitest/.test(s.test) ? "vitest" : /jest/.test(s.test) ? "jest" : "generic";
    out.push(gate("unit", "test", "functional", pm, run("test"), parser, 600_000));
  }
  return out;
}

/** The template id for a repository, from its manifests and lockfiles. */
export function detectGateTemplate(root: string): GateTemplateId | undefined {
  const has = (f: string) => existsSync(join(root, f));
  if (has("package.json")) {
    if (has("pnpm-lock.yaml") || has("pnpm-workspace.yaml")) return "pnpm";
    if (has("yarn.lock")) return "yarn";
    if (has("package-lock.json")) return "npm";
    return "pnpm";
  }
  if (has("pyproject.toml") || has("setup.py") || has("requirements.txt")) return "python";
  if (has("Cargo.toml")) return "rust";
  if (has("go.mod")) return "go";
  return undefined;
}

/** The gates of a template for `root`; undefined when nothing is recognised. */
export function gateTemplate(
  root: string,
  id = detectGateTemplate(root),
): GateDefinition[] | undefined {
  switch (id) {
    case "pnpm":
    case "npm":
    case "yarn": {
      const gates = jsTemplate(id, root);
      return gates.length > 0 ? gates : undefined;
    }
    case "python":
      return [
        gate("lint", "lint", "static", "python3", ["-m", "ruff", "check", "."], "generic", 120_000),
        gate("typecheck", "typecheck", "static", "python3", ["-m", "mypy", "."], "generic"),
        gate("unit", "test", "functional", "python3", ["-m", "pytest", "-q"], "generic", 600_000),
      ];
    case "rust":
      return [
        gate("typecheck", "typecheck", "static", "cargo", ["check", "--all-targets"], "cargo"),
        gate(
          "lint",
          "lint",
          "static",
          "cargo",
          ["clippy", "--all-targets", "--", "-D", "warnings"],
          "cargo",
        ),
        gate("unit", "test", "functional", "cargo", ["test"], "cargo", 900_000),
      ];
    case "go":
      return [
        gate("typecheck", "typecheck", "static", "go", ["build", "./..."], "generic"),
        gate("lint", "lint", "static", "go", ["vet", "./..."], "generic"),
        gate("unit", "test", "functional", "go", ["test", "./..."], "generic", 600_000),
      ];
    default:
      return undefined;
  }
}

/** A template rendered as a `gates.toml` the project can pin and edit. */
export function renderGatesToml(gates: GateDefinition[], maxFiles = 3, maxDiffLines = 200): string {
  const q = (v: string) => JSON.stringify(v);
  return [
    "# Generated by `sekhemet gates init` from the project's manifests (G27).",
    "[project]",
    `max_files = ${maxFiles}`,
    `max_diff_lines = ${maxDiffLines}`,
    "",
    ...gates.flatMap((g) => [
      "[[gate]]",
      `id = ${q(g.id)}`,
      `rung = ${q(g.rung)}`,
      `layer = ${q(g.layer)}`,
      `command = ${q(g.command)}`,
      `args = [${g.args.map(q).join(", ")}]`,
      `timeout_s = ${Math.round(g.timeoutMs / 1000)}`,
      `parser = ${q(g.parser)}`,
      "",
    ]),
  ].join("\n");
}
