import { createHash } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import type { EventLog } from "./log.js";

/**
 * Project documents generated from the ledger (design-stage
 * NEW-design-stage-3: DS-N3-1, -2, -3, -5, -7).
 *
 * Each export is one `docs/exported {seq, noNames, files: [{path, sha256,
 * kind}]}` event: the ledger `seq` the documents were generated from — the
 * same `seq` their generated header names — and each file's
 * repository-relative path and SHA-256. A merged commit that changes an
 * exported document is parsed by the exporter and diffed against the ledger;
 * the kernel records the diff (`docs/import_diffed`) as one proposal per
 * difference (`DOCP-<n>`), and nothing in the ledger changes until a person
 * applies one (`docs/proposal_applied`; the caller then makes the change
 * under that person's principal) or dismisses it. A file without the
 * generated header is offered the same way (DS-N3-5). The proposed text is
 * private; `README.md` and `CONTRIBUTING.md` are never exported (DS-N3-7).
 */
export type ProjectDocumentKind = "brief" | "requirements" | "decision" | "changelog" | "release";

export const PROJECT_DOCUMENT_KINDS: readonly ProjectDocumentKind[] = [
  "brief",
  "requirements",
  "decision",
  "changelog",
  "release",
];

const HEADER = /^<!-- Generated by Sekhemet from ledger seq (\d+)\b[^\n]*-->/;

/** The first line of a generated document: the ledger `seq` it was generated from (DS-N3-1). */
export function generatedHeader(seq: number): string {
  return `<!-- Generated by Sekhemet from ledger seq ${seq}. Changes to this file become proposals. -->`;
}

/** The `seq` a document's generated header names, or undefined when it has none (DS-N3-5). */
export function readGeneratedHeader(text: string): number | undefined {
  const m = HEADER.exec(text.replace(/^﻿/, ""));
  return m ? Number(m[1]) : undefined;
}

export interface ExportedFile {
  /** Repository-relative, with `/`. */
  path: string;
  sha256: string;
  kind: ProjectDocumentKind;
}

export type DocumentTarget = "brief" | "requirement" | "decision";

export interface DocumentDifference {
  kind: "added" | "removed" | "changed";
  target: DocumentTarget;
  /** The requirement or decision id; absent for an addition or the brief. */
  targetId?: string;
  /** The field that differs (`title`, `criteria`, `problem`, …). */
  field?: string;
  /** What the document now says: private. */
  proposed?: string;
}

export interface DocumentProposal extends DocumentDifference {
  id: string;
  path: string;
  /** The project whose repository holds the document (DEC-57); absent from before. */
  projectId?: string;
  commit: string;
  state: "open" | "applied" | "dismissed";
}

const SHA256 = /^[0-9a-f]{64}$/;
const COMMIT = /^(?:[0-9a-f]{7,40}|[0-9a-f]{64})$/;
/** Left to the person; an export offers a change to them only as a proposal (DS-N3-7). */
const PERSON_FILES = new Set(["readme.md", "contributing.md"]);

function checkPath(path: string): void {
  const parts = path.split("/");
  if (
    !path ||
    path.startsWith("/") ||
    /^[A-Za-z]:/.test(path) ||
    path.includes("\\") ||
    parts.some((p) => p === ".." || p === "." || p === "")
  ) {
    throw new Error(
      `An exported document's path is repository-relative and inside the repository: ${path}`,
    );
  }
  if (parts.length === 1 && PERSON_FILES.has(path.toLowerCase())) {
    throw new Error(
      `${path} is the person's: an export offers a change to it as a proposal, never writes it`,
    );
  }
}

/** Whether a record of `own` project counts for `wanted`: either unnamed, or the same (DEC-57). */
function sameProject(own: string | undefined, wanted: string | undefined): boolean {
  return wanted === undefined || own === undefined || own === wanted;
}

interface Row {
  seq: number;
  type: string;
  payload: string;
}

export class ProjectDocumentLedger {
  constructor(
    private readonly db: DatabaseSync,
    private readonly log: EventLog,
  ) {}

  private head(): number {
    return (
      (this.db.prepare("SELECT MAX(seq) AS s FROM events").get() as { s: number | null }).s ?? 0
    );
  }

  /** Record one export (DS-N3-1, -3): the seq it was generated from, and each file's path and SHA-256. */
  public async recordExport(
    input: { seq: number; noNames: boolean; files: ExportedFile[]; projectId?: string | undefined },
    actor = "planner",
  ): Promise<void> {
    if (!Number.isInteger(input.seq) || input.seq < 1 || input.seq > this.head()) {
      throw new Error(
        `An export is generated from a seq the ledger holds (1–${this.head()}), got ${input.seq}`,
      );
    }
    const paths = new Set<string>();
    for (const f of input.files) {
      checkPath(f.path);
      if (paths.has(f.path)) throw new Error(`${f.path} is exported twice`);
      paths.add(f.path);
      if (!SHA256.test(f.sha256)) throw new Error(`${f.path}: the SHA-256 is 64 hex digits`);
      if (!PROJECT_DOCUMENT_KINDS.includes(f.kind)) {
        throw new Error(`${f.path}: a document is one of ${PROJECT_DOCUMENT_KINDS.join(", ")}`);
      }
    }
    await this.log.append({
      actor,
      type: "docs/exported",
      payload: {
        seq: input.seq,
        noNames: input.noNames,
        ...(input.projectId ? { projectId: input.projectId } : {}),
        files: input.files.map((f) => ({ path: f.path, sha256: f.sha256, kind: f.kind })),
      },
    });
  }

  /**
   * Every export, oldest first; with `projectId`, that project's (DEC-57: each
   * project keeps its own repository, so the same path in two projects is two
   * documents). An export recorded before exports named their project counts
   * for every project.
   */
  public exports(projectId?: string): {
    exportSeq: number;
    seq: number;
    noNames: boolean;
    projectId?: string;
    files: ExportedFile[];
  }[] {
    return (
      this.db
        .prepare("SELECT seq, type, payload FROM events WHERE type = 'docs/exported' ORDER BY seq")
        .all() as unknown as Row[]
    )
      .map((r) => {
        const p = JSON.parse(r.payload) as {
          seq: number;
          noNames: boolean;
          projectId?: string;
          files: ExportedFile[];
        };
        return {
          exportSeq: r.seq,
          seq: p.seq,
          noNames: p.noNames,
          ...(p.projectId ? { projectId: p.projectId } : {}),
          files: p.files,
        };
      })
      .filter((e) => sameProject(e.projectId, projectId));
  }

  /** The last export of a path (in a project, when given): its SHA-256, kind and generating seq; undefined when never exported. */
  public lastExport(
    path: string,
    projectId?: string,
  ): (ExportedFile & { seq: number; exportSeq: number }) | undefined {
    let out: (ExportedFile & { seq: number; exportSeq: number }) | undefined;
    for (const e of this.exports(projectId)) {
      const f = e.files.find((x) => x.path === path);
      if (f) out = { ...f, seq: e.seq, exportSeq: e.exportSeq };
    }
    return out;
  }

  private nextProposalNumber(): number {
    let n = 0;
    for (const r of this.db
      .prepare("SELECT payload FROM events WHERE type = 'docs/import_diffed'")
      .all() as unknown as { payload: string }[]) {
      n += (JSON.parse(r.payload) as { proposals: unknown[] }).proposals.length;
    }
    return n + 1;
  }

  /**
   * Record a merged commit's changes to an exported document as one proposal
   * per difference (DS-N3-2, -5). The file's SHA-256 and its header's seq are
   * computed here from its text; the text itself is not recorded.
   */
  public async recordImportDiff(
    input: {
      path: string;
      commit: string;
      text: string;
      differences: DocumentDifference[];
      projectId?: string | undefined;
    },
    actor = "planner",
  ): Promise<string[]> {
    checkPath(input.path);
    if (!this.lastExport(input.path, input.projectId)) {
      throw new Error(
        `${input.path} was never exported: only a generated document's changes become proposals`,
      );
    }
    if (!COMMIT.test(input.commit)) throw new Error(`Not a git commit: ${input.commit}`);
    let n = this.nextProposalNumber();
    const proposals = input.differences.map((d) => ({
      id: `DOCP-${n++}`,
      kind: d.kind,
      target: d.target,
      ...(d.targetId !== undefined ? { targetId: d.targetId } : {}),
      ...(d.field !== undefined ? { field: d.field } : {}),
    }));
    const headerSeq = readGeneratedHeader(input.text);
    const proposed = Object.fromEntries(
      input.differences
        .map((d, i) => [proposals[i]?.id as string, d.proposed] as const)
        .filter(([, text]) => text !== undefined),
    );
    await this.log.append({
      actor,
      type: "docs/import_diffed",
      payload: {
        path: input.path,
        ...(input.projectId ? { projectId: input.projectId } : {}),
        commit: input.commit,
        sha256: createHash("sha256").update(input.text).digest("hex"),
        ...(headerSeq !== undefined ? { headerSeq } : {}),
        proposals,
      },
      ...(Object.keys(proposed).length > 0 ? { private: { proposed } } : {}),
    });
    return proposals.map((p) => p.id);
  }

  /** Every import proposal (of a project, when given) with where it stands, and its private text. */
  public async proposals(projectId?: string): Promise<DocumentProposal[]> {
    const byId = new Map<string, DocumentProposal>();
    for (const e of await this.log.getEventsByTypes([
      "docs/import_diffed",
      "docs/proposal_applied",
      "docs/proposal_dismissed",
    ])) {
      const p = e.payload as Record<string, unknown>;
      if (e.type === "docs/import_diffed") {
        const texts = (e.private?.proposed ?? {}) as Record<string, unknown>;
        for (const d of p.proposals as Omit<DocumentProposal, "path" | "commit" | "state">[]) {
          byId.set(d.id, {
            ...d,
            ...(typeof texts[d.id] === "string" ? { proposed: texts[d.id] as string } : {}),
            path: String(p.path),
            ...(typeof p.projectId === "string" ? { projectId: p.projectId } : {}),
            commit: String(p.commit),
            state: "open",
          });
        }
        continue;
      }
      const d = byId.get(String(p.id));
      if (d && d.state === "open")
        d.state = e.type === "docs/proposal_applied" ? "applied" : "dismissed";
    }
    return [...byId.values()].filter((d) => sameProject(d.projectId, projectId));
  }

  public async openProposals(projectId?: string): Promise<DocumentProposal[]> {
    return (await this.proposals(projectId)).filter((p) => p.state === "open");
  }

  private async mustOpen(id: string): Promise<DocumentProposal> {
    const d = (await this.proposals()).find((p) => p.id === id);
    if (!d) throw new Error(`No document proposal ${id}`);
    if (d.state !== "open") throw new Error(`Document proposal ${id} was already ${d.state}`);
    return d;
  }

  /** A person applies a proposal (DS-N3-2); the caller then changes the ledger under that principal. */
  public async applyProposal(id: string, principal: string): Promise<DocumentProposal> {
    if (!principal)
      throw new Error("A document proposal is applied by a person; no principal was given");
    const d = await this.mustOpen(id);
    await this.log.append({
      actor: "human",
      type: "docs/proposal_applied",
      payload: { id },
      principal,
    });
    return { ...d, state: "applied" };
  }

  public async dismissProposal(id: string, principal: string): Promise<void> {
    if (!principal)
      throw new Error("A document proposal is dismissed by a person; no principal was given");
    await this.mustOpen(id);
    await this.log.append({
      actor: "human",
      type: "docs/proposal_dismissed",
      payload: { id },
      principal,
    });
  }
}
