import type { Requirement } from "@sekhemet/kernel";
import type { PlannerDecision } from "@sekhemet/planner";
import { describe, expect, it } from "vitest";
import {
  diffBrief,
  diffDecision,
  diffRequirements,
  parseRequirements,
} from "../src/project_docs.js";

// design-stage DS-N3-2 and DEC-44: a generated project document a person
// edited is read back as Markdown by one parser (marked), not line by line,
// so a code block, a later section or a wrapped line is read as Markdown
// means it. Every reading the documents had before is kept: the heading per
// requirement, the meta line with its MoSCoW `priority:` (and an older
// document's `kano:` and `must:`), criteria with and without ids, the
// invariant line left out, the brief's baseline and a decision's outcome.

const REQS = `<!-- generated by sekhemet from the ledger at seq 42; edit and a proposal is recorded -->
# Requirements: Recipes

Status as of the latest check of main, against the internal tool profile.

### REQ-1 — Save a recipe

version: 2 · priority: Must have · release: SLICE-1 · status: done · dependsOn: none

- \`REQ-1.1\` WHEN a person saves a recipe THE SYSTEM SHALL list it
- invariant: a saved recipe is never lost

Tests: \`tests/save.spec.ts > lists a saved recipe\`

### REQ-2 — Tag a recipe

version: 1 · priority: Could have · release: SLICE-2 · status: planned · dependsOn: REQ-1, REQ-3

- A tag can be removed

Tests: none yet

### A new idea
`;

const req = (patch: Partial<Requirement>): Requirement =>
  ({
    id: "REQ-2",
    title: "Tag a recipe",
    version: 1,
    mustHave: false,
    kano: "attractive",
    sliceId: "SLICE-1",
    dependsOn: [],
    criteria: [],
    ...patch,
  }) as Requirement;

describe("DS-N3-2, DEC-44: a requirements document is read as Markdown", () => {
  it("reads each requirement's heading, meta line and criteria as generated", () => {
    expect(parseRequirements(REQS)).toEqual([
      {
        id: "REQ-1",
        title: "Save a recipe",
        priority: "Must have",
        dependsOn: [],
        criteria: [
          { id: "REQ-1.1", text: "WHEN a person saves a recipe THE SYSTEM SHALL list it" },
        ],
      },
      {
        id: "REQ-2",
        title: "Tag a recipe",
        priority: "Could have",
        dependsOn: ["REQ-1", "REQ-3"],
        criteria: [{ text: "A tag can be removed" }],
      },
      { title: "A new idea", criteria: [] },
    ]);
  });

  it("still reads an older document's kano: and must:", () => {
    const old = "### REQ-2 — Tag a recipe\n\nversion: 1 · kano: performance · must: yes\n";
    expect(parseRequirements(old)).toEqual([
      { id: "REQ-2", title: "Tag a recipe", kano: "performance", must: true, criteria: [] },
    ]);
  });

  it("does not read a heading or a list inside a code block", () => {
    const doc = [
      "### REQ-2 — Tag a recipe",
      "",
      "- A tag can be removed",
      "",
      "```md",
      "### REQ-9 — An example, not a requirement",
      "- `REQ-9.1` an example criterion",
      "```",
      "",
    ].join("\n");
    expect(parseRequirements(doc)).toEqual([
      { id: "REQ-2", title: "Tag a recipe", criteria: [{ text: "A tag can be removed" }] },
    ]);
  });

  it("ends a requirement at the next section, so a later list is not its criteria", () => {
    const doc =
      "### REQ-2 — Tag a recipe\n\n- A tag can be removed\n\n## Notes\n\n- ask the team\n";
    expect(parseRequirements(doc)[0]?.criteria).toEqual([{ text: "A tag can be removed" }]);
    expect(diffRequirements(doc, [req({ criteria: [{ id: "REQ-2.1", text: "x" }] })])).toEqual([
      {
        kind: "changed",
        target: "requirement",
        targetId: "REQ-2",
        field: "criteria",
        proposed: JSON.stringify([{ text: "A tag can be removed" }]),
      },
    ]);
  });

  it("keeps a criterion a person wrapped onto a second line whole, and reads any bullet", () => {
    const doc = [
      "### REQ-2 — Tag a recipe",
      "",
      "- `REQ-2.1` WHEN a person removes a tag",
      "  THE SYSTEM SHALL keep the recipe",
      "* A tag has a colour",
      "",
    ].join("\n");
    expect(parseRequirements(doc)[0]?.criteria).toEqual([
      { id: "REQ-2.1", text: "WHEN a person removes a tag THE SYSTEM SHALL keep the recipe" },
      { text: "A tag has a colour" },
    ]);
  });
});

describe("DS-N3-2, DEC-44: the brief and a decision record are read as Markdown", () => {
  it("reads the baseline section whole, a heading inside a code block included", () => {
    const brief = [
      "# Product brief: Recipes",
      "",
      "## What people have today",
      "",
      "A spreadsheet with one tab per cook:",
      "",
      "```",
      "## Soups",
      "```",
      "",
      "## Type",
      "",
      "Internal tool.",
      "",
    ].join("\n");
    expect(diffBrief(brief, "A spreadsheet")).toEqual([
      {
        kind: "changed",
        target: "brief",
        field: "baseline",
        proposed: "A spreadsheet with one tab per cook:\n\n```\n## Soups\n```",
      },
    ]);
    expect(diffBrief(brief, "A spreadsheet with one tab per cook:\n\n```\n## Soups\n```")).toEqual(
      [],
    );
    expect(diffBrief("# Product brief\n\n## Type\n", "x")).toEqual([]);
  });

  it("reads the chosen option from the outcome, never from a code block", () => {
    const decision = {
      id: "dec_1",
      request: { options: [{ label: "SQLite" }, { label: "Postgres" }] },
      record: { selectedOptionIndex: 0 },
    } as unknown as PlannerDecision;
    const doc = (chosen: string) =>
      [
        "# Which database?",
        "",
        "## Context and Problem Statement",
        "",
        "```",
        'Chosen option: "Mongo", because an example.',
        "```",
        "",
        "## Decision Outcome",
        "",
        `Chosen option: "${chosen}", because it is small.`,
        "",
      ].join("\n");
    expect(diffDecision(doc("SQLite"), decision)).toEqual([]);
    expect(diffDecision(doc("Postgres"), decision)).toEqual([
      {
        kind: "changed",
        target: "decision",
        targetId: "dec_1",
        field: "outcome",
        proposed: "Postgres",
      },
    ]);
  });
});
